platform :ios, '15.5'

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end

target 'TFLiteExample' do
  use_frameworks!
  pod 'WildEdge', :path => '../..'
  pod 'TensorFlowLiteSwift',       '~> 2.14'
  pod 'TensorFlowLiteSwift/Metal', '~> 2.14'
end
