name: WildEdgeiOSSample
options:
  bundleIdPrefix: dev.wildedge.sample
  deploymentTarget:
    iOS: "14.0"
packages:
  WildEdge:
    path: ../../WildEdge
targets:
  WildEdgeiOSSample:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.wildedge.sample.ios
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: "NO"
        INFOPLIST_FILE: Sources/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: WildEdge
        product: WildEdge
