platform :ios, '15.5'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end

target 'TFLiteObjcExample' do
  use_frameworks!
  pod 'WildEdge', :path => '../..'
  pod 'TensorFlowLiteObjC', '~> 2.17'
end
