name: TFLiteObjcExample
options:
  bundleIdPrefix: dev.wildedge
schemes:
  TFLiteObjcExample:
    build:
      targets:
        TFLiteObjcExample: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
targets:
  TFLiteObjcExample:
    type: application
    platform: iOS
    deploymentTarget: "15.5"
    sources:
      - path: Sources/TFLiteObjcExample
    info:
      path: Sources/TFLiteObjcExample/Info.plist
      properties:
        CFBundleIdentifier: dev.wildedge.TFLiteObjcExample
        UILaunchScreen: {}
    settings:
      base:
        CLANG_ENABLE_MODULES: YES
        HEADER_SEARCH_PATHS: $(inherited) $(PODS_ROOT)/TensorFlowLiteObjC/tensorflow/lite/objc/apis
