platform :ios, '15.5'

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end

target 'MLKitExample' do
  use_frameworks!
  pod 'WildEdge', :path => '../..'
  pod 'GoogleMLKit/FaceDetection',      '~> 9.0'
  pod 'GoogleMLKit/ObjectDetection',    '~> 9.0'
  pod 'GoogleMLKit/ImageLabeling',      '~> 9.0'
  pod 'GoogleMLKit/TextRecognition',    '~> 9.0'
  pod 'GoogleMLKit/BarcodeScanning',    '~> 9.0'
  pod 'GoogleMLKit/PoseDetection',      '~> 9.0'
end
